version: "3.7"

# You need to set many environment variables for this to work.

services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
     driver: none

  clockwork_web-dev:
    image: clockwork_web
    depends_on:
      - mongodb
    working_dir: /clockwork
    volumes:
      - ./clockwork_web:/clockwork/clockwork_web
      - ./test_config.toml:/clockwork/test_config.toml
    ports:
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
    command:
      flask run --host=0.0.0.0

  clockwork_web_test:
    image: clockwork_web_test
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ./clockwork_web:/clockwork/clockwork_web
      - ./clockwork_web_test:/clockwork/clockwork_web_test
      - ./test_common:/clockwork/test_common
      - ./test_config.toml:/clockwork/test_config.toml
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}

  clockwork_tools_test:
    image: clockwork_tools_test
    depends_on:
      - mongodb
      - clockwork_web-dev
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ./clockwork_tools:/clockwork/clockwork_tools
      - ./clockwork_tools_test:/clockwork/clockwork_tools_test
      - ./test_common:/clockwork/test_common
      - ./test_config.toml:/clockwork/test_config.toml
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_HOST: "clockwork_web-dev"
      clockwork_tools_test_PORT: ${FLASK_RUN_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  slurm_state_test:
    image: slurm_state_test
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ./slurm_state:/clockwork/slurm_state
      - ./slurm_state_test:/clockwork/slurm_state_test
      - ./test_config.toml:/clockwork/test_config.toml
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml

  clockwork_dev:
    image: clockwork_dev
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    ports:
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - ./clockwork_tools:/clockwork/clockwork_tools
      - ./clockwork_tools_test:/clockwork/clockwork_tools_test
      - ./clockwork_web:/clockwork/clockwork_web
      - ./clockwork_web_test:/clockwork/clockwork_web_test
      - ./slurm_state:/clockwork/slurm_state
      - ./slurm_state_test:/clockwork/slurm_state_test
      - ./scripts:/clockwork/scripts
      - ./scripts_test:/clockwork/scripts_test
      - ./test_common:/clockwork/test_common
      - ./test_config.toml:/clockwork/test_config.toml
    command: bash
    stdin_open: true
    tty: true
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml
      clockwork_tools_test_HOST: "localhost"
      clockwork_tools_test_PORT: ${FLASK_RUN_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  clockwork_scripts:
    image: clockwork_scripts
    container_name: cw-scripts
    build:
      context: ./
      dockerfile: scripts/Dockerfile
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ${CLOCKWORK_SLURM_REPORT_PATH}:/clockwork/tmp/slurm_report
      - ./test_common:/clockwork/test_common
      - ./test_config.toml:/clockwork/test_config.toml
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml

  scripts_test:
    image: scripts_test
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ./scripts:/clockwork/scripts
      - ./scripts_test:/clockwork/scripts_test
      - ./test_config.toml:/clockwork/test_config.toml
    environment:
      CLOCKWORK_CONFIG: /clockwork/test_config.toml
