version: "3.7"

# You need to set many environment variables for this to work.

services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
     driver: none

  clockwork_web_test:
    image: clockwork_web_test
    depends_on:
      - mongodb
    ports:
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    working_dir: /clockwork
    volumes:
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
    environment:
      LOGIN_DISABLED: "True"
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  clockwork_tools_test:
    image: clockwork_tools_test
    depends_on:
      - mongodb
    working_dir: /clockwork
    volumes:
      - ../clockwork_tools:/clockwork/clockwork_tools
      - ../clockwork_tools_test:/clockwork/clockwork_tools_test
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
    environment:
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_HOST: ${clockwork_tools_test_HOST}
      clockwork_tools_test_PORT: ${clockwork_tools_test_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  clockwork_dev:
    image: clockwork_tools_test
    depends_on:
      - mongodb
    working_dir: /clockwork
    volumes:
      - ../clockwork_tools:/clockwork/clockwork_tools
      - ../clockwork_tools_test:/clockwork/clockwork_tools_test
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
    command: bash
    stdin_open: true
    tty: true
    environment:
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_HOST: ${clockwork_tools_test_HOST}
      clockwork_tools_test_PORT: ${clockwork_tools_test_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}
