version: "3.7"

# You need to set many environment variables for this to work.

services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
     driver: none

  clockwork_web-dev:
    image: clockwork_web
    depends_on:
      - mongodb
    working_dir: /clockwork
    volumes:
      - ../clockwork_web:/clockwork/clockwork_web
    ports:
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    environment:
      LOGIN_DISABLED: "True"
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
    command:
      flask run --host=0.0.0.0

  clockwork_web_test:
    image: clockwork_web_test
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
      - ../test_common:/clockwork/test_common
    environment:
      LOGIN_DISABLED: "True"
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  clockwork_tools_test:
    image: clockwork_tools_test
    depends_on:
      - mongodb
      - clockwork_web-dev
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ../clockwork_tools:/clockwork/clockwork_tools
      - ../clockwork_tools_test:/clockwork/clockwork_tools_test
      - ../test_common:/clockwork/test_common
    environment:
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_HOST: "clockwork_web-dev"
      clockwork_tools_test_PORT: ${FLASK_RUN_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}

  slurm_state_test:
    image: slurm_state_test
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    volumes:
      - ../slurm_state:/clockwork/slurm_state
      - ../slurm_state_test:/clockwork/slurm_state_test
    environment:
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      slurm_state_ALLOCATIONS_RELATED_TO_MILA: "/clockwork/slurm_state_test/fake_allocations_related_to_mila.json"

  clockwork_dev:
    image: clockwork_dev
    depends_on:
      - mongodb
    user: "${CLOCKWORK_UID}:${CLOCKWORK_GID}"
    working_dir: /clockwork
    ports:
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - ../clockwork_tools:/clockwork/clockwork_tools
      - ../clockwork_tools_test:/clockwork/clockwork_tools_test
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
      - ../slurm_state:/clockwork/slurm_state
      - ../slurm_state_test:/clockwork/slurm_state_test
      - ../test_common:/clockwork/test_common
    command: bash
    stdin_open: true
    tty: true
    environment:
      MONGODB_DATABASE_NAME: "clockwork"
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      clockwork_tools_test_HOST: "localhost"
      clockwork_tools_test_PORT: ${FLASK_RUN_PORT}
      clockwork_tools_test_EMAIL: ${clockwork_tools_test_EMAIL}
      clockwork_tools_test_CLOCKWORK_API_KEY: ${clockwork_tools_test_CLOCKWORK_API_KEY}
      # note that this file is not included in the repository under normal circumstances
      slurm_state_ALLOCATIONS_RELATED_TO_MILA: "/clockwork/slurm_state/allocations_related_to_mila.json"
