version: "3.7"

# You need to set the environment variables UID and GID
# for this recipe to work.

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 19090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Note that we are not persisting the data outside of the container.
    # This is not a great long-term solution for Prometheus,
    # but it's perfect for testing the Clockwork code.

  grafana:
    image: grafana/grafana:latest-ubuntu
    ports:
      - 13000:3000
    user: "${UID}:${GID}"
    volumes:
      - ./grafana_unprotected.ini:/etc/grafana/grafana.ini
    # Note that we are not persisting the data outside of the container.
    # This is not a great long-term solution for Grafana because
    # it doesn't save any of our nice graphs, but it's fine for
    # testing the Clockwork code.

  elasticsearch:
    image: elasticsearch:7.12.1
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      discovery.type: single-node
    # Note that we are not persisting the data outside of the container.
    # This is not a great long-term solution for ElasticSearch because
    # but it's fine for testing the Clockwork code.

  mongodb:
    image: mongo
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

# TODO : Maybe find way to specify the ssh public/private keys as mount.
#        This is something you should develop in isolation before trying
#        to wrap it into a Docker Compose recipe.

# TODO : Create an executable file in the scraper that does
#        - install dependencies
#        - make sure the current code is found
#        if testing mode:
#          - run the cluster monitor with fake data forever
#        otherwise:
#          - ssh copy over the executable on the cluster
#          - run the cluster monitor forever

  clockwork_web:
    image: python:3.9-buster
    ports:
      # Any exterior port works, but let's pick 15000 to make it more unique
      # and avoid some potential conflicts with other Flask servers on the host.
      # At the same time, let's keep 5000 for services running inside the
      # container to make it more predictible.
      - ${EXTERNAL_FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    working_dir: /clockwork
    volumes:
      - ../clockwork_web:/clockwork/clockwork_web
      - ../clockwork_web_test:/clockwork/clockwork_web_test
      - ../mila_tools:/clockwork/mila_tools
      - ../mila_tools_test:/clockwork/mila_tools_test
      - ./entrypoint_inside_clockwork_web_container.sh:/clockwork/entrypoint_inside_clockwork_web_container.sh
    command: bash /clockwork/entrypoint_inside_clockwork_web_container.sh
    # command: bash -c "sleep 43897423"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      CLOCKWORK_TASK: ${CLOCKWORK_TASK}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      MILA_TOOLS_TEST_HOST: clockwork_web  # name of this very service
      MILA_TOOLS_TEST_PORT: ${FLASK_RUN_PORT}
      MILA_TOOLS_TEST_EMAIL: ${MILA_TOOLS_TEST_EMAIL}
      MILA_TOOLS_TEST_API_KEY: ${MILA_TOOLS_TEST_API_KEY}

# TODO : This    CLOCKWORK_TASK: ${CLOCKWORK_TASK}    will go elsewhere as well.