"""
Stores the users contained in a json file, as generated by
"produce_fake_users.py".
"""

import os
import sys
import argparse

from slurm_state.mongo_client import get_mongo_client
from slurm_state.mongo_update import main_read_users_and_update_collection


def main(argv):
    # Retrieve the args
    parser = argparse.ArgumentParser(
        prog=argv[0],
        description="Stores users in the Clockwork database.",
    )

    parser.add_argument(
        "-u",
        "--users_file",
        help="JSON file presenting the users to insert in the database.",
    )

    parser.add_argument(
        "--mongodb_collection", default="clockwork", help="Collection to populate."
    )

    args = parser.parse_args(argv[1:])

    users_file = args.users_file
    assert os.path.exists(users_file)

    # Open the database and insert the users
    client = get_mongo_client()
    users_collection = client[args.mongodb_collection]["users"]

    users_collection.create_index(
        [("mila_email_username", 1)], name="users_email_index"
    )

    main_read_users_and_update_collection(
        users_collection,
        users_file,
    )


if __name__ == "__main__":
    main(sys.argv)
