global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
rule_files:
- /etc/prometheus/rules.yml
scrape_configs:
- job_name: bibliotheque
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:19997
    labels:
      instance: monitoring
- job_name: slurm_sinfo
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:19998
    labels:
      instance: monitoring