global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
rule_files:
- /etc/prometheus/rules.yml
scrape_configs:
- job_name: bibliotheque
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:19997
    labels:
      instance: monitoring
- job_name: mila_slurm_sinfo
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:17001
    labels:
      instance: monitoring
      cluster_name: mila
- job_name: beluga_slurm_sinfo
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:17002
    labels:
      instance: monitoring
      cluster_name: beluga
- job_name: graham_slurm_sinfo
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:17003
    labels:
      instance: monitoring
      cluster_name: graham
- job_name: cedar_slurm_sinfo
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:17004
    labels:
      instance: monitoring
      cluster_name: cedar