name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==22.3.0 coverage Babel
    - name: Check code with Black
      run: |
        black --check .
    - name: Compile translation files
      run: |
        pybabel compile -i clockwork_web/static/locales/fr/LC_MESSAGES/messages.po -o clockwork_web/static/locales/fr/LC_MESSAGES/check_messages.mo
    - name: Assert the translation files are the same
      run: |
        if ! cmp clockwork_web/static/locales/fr/LC_MESSAGES/messages.mo clockwork_web/static/locales/fr/LC_MESSAGES/check_messages.mo; then exit 3; fi
    - name: Run tests
      run: |
        sh test.sh
    - name: Report coverage
      run: |
        sh cov.sh
