name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==22.3.0 coverage
    - name: Check code with Black
      run: |
        black --check .
    - name: Run tests
      run: |
        sh test.sh
    - name: Report coverage
      run: |
        sh cov.sh
